### ISSUE TITLE
Crash while calling performClick

### ISSUE THREAD

**Issue by michaelrhughes** [gabrielemariotti/cardslib#339]
I experienced the following crash when programatically calling perform click on a CardView in a list. I was scrolling around while clicking so I suspect that the view was in the process of being recycled and didn't have a parent. The version I am using is:

compile ('com.github.gabrielemariotti.cards:library:1.5.0') 

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
            at it.gmariotti.cardslib.library.view.CardListView$ExpandCollapseHelper.findDirectChild(CardListView.java:382)
            at it.gmariotti.cardslib.library.view.CardListView$ExpandCollapseHelper.access$000(CardListView.java:296)
            at it.gmariotti.cardslib.library.view.CardListView$ExpandCollapseHelper$2.<init>(CardListView.java:347)
            at it.gmariotti.cardslib.library.view.CardListView$ExpandCollapseHelper.animateExpanding(CardListView.java:344)
            at it.gmariotti.cardslib.library.view.CardListView.onExpandStart(CardListView.java:270)
            at it.gmariotti.cardslib.library.view.CardView$TitleViewOnClickListener.animateExpanding(CardView.java:739)
            at it.gmariotti.cardslib.library.view.CardView$TitleViewOnClickListener.onClick(CardView.java:726)
            at android.view.View.performClick(View.java:4438)

**Comment by EliMadDev** [comment]
same problem on the latest version,
any fixes?
thanks
