### ISSUE TITLE
extras have a bug

### ISSUE THREAD

**Issue by zeshaoaaa** [gabrielemariotti/cardslib#546]
I have not change the source code.

Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
                                                                                           at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:360)
                                                                                           at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
                                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
                                                                                           at it.gmariotti.cardslib.demo.extras.ui.BaseActivity.setContentView(BaseActivity.java:184)
                                                                                           at it.gmariotti.cardslib.demo.extras.ui.NativeMenuActivity.onCreate(NativeMenuActivity.java:47)
                                                                                           at android.app.Activity.performCreate(Activity.java:6092)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
                                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:178) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                           at android.os.Looper.loop(Looper.java:194) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5624) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372)

**Comment by anukools** [comment]
hey @zeshaoaaa  have you resolved this issue..?

**Comment by zeshaoaaa** [comment]
@anukools Not yet. I am using official CardView now, may be you can try to use it. not bad for me.
